### ISSUE TITLE
Can't find Subscription ID

### ISSUE THREAD

**Issue by tkav** [stevenocchipinti/optus-mobile-usage#1]
Hi @stevenocchipinti, I can't find the SUBSCRIPTION_ID anywhere in the AJAX requests. Do you have any tips on where to locate it?

**Comment by stevenocchipinti** [comment]
Hello,

I'm sorry, this project is inactive and I don't think it even works anymore 😅 
I'm guessing the website has changed since.

Cheers

**Comment by tkav** [comment]
I was so close to having a PHP port of this haha. Thanks Steven
